component: cart
params: "REDIS_HOST:prod.elasticache.endpoint,CATALOGUE_HOST:catalogue,CATALOGUE_PORT:8080"



#  Environment=REDIS_HOST={{ lookup('amazon.aws.aws_ssm', '{{env}}.elasticache.endpoint', region='us-east-1')}}
#  Environment=CATALOGUE_HOST={{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.catalogue_host', region='us-east-1')}}
#  Environment=CATALOGUE_PORT={{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.catalogue_port', region='us-east-1')}}
